spring.profiles.active: dev
greeting.message: helo im config server from git updated one
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/corflowschema?createDatabaseIfNotExist=true
    username: root
    password: Anand@123 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
